# SPDX-FileCopyrightText: © 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
apiVersion: v1
kind: Service
metadata:
  name: logging-ai-api
  namespace: logging
  labels:
    app.kubernetes.io/name: logging-ai-api
    app.kubernetes.io/component: ai
spec:
  selector:
    app.kubernetes.io/name: logging-ai-api
  ports:
    - name: http
      port: 9090
      targetPort: 9090
