# SPDX-FileCopyrightText:  © 2024 Siemens Healthineers AG
# SPDX-License-Identifier:   MIT

# Build the contextfolder server container, after precompilation was done in Linux VM
#
# __BEGIN_BuildImage_Variables__
# ImageName:      k2s.registry.local/weather-win
# ExeName:        weather-win.exe
# __END_BuildImage_Variables__
#

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
COPY weather-win.exe .
ENTRYPOINT ["weather-win.exe"]