# SPDX-FileCopyrightText: © 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
# Source: nginx-gateway-fabric/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-gw-controller
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.6.3
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.6.3"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - create
      - update
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - update
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - httproutes
      - referencegrants
      - grpcroutes
      - backendtlspolicies
      - tlsroutes
      - listenersets
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes/status
      - gateways/status
      - gateways/finalizers
      - gatewayclasses/status
      - grpcroutes/status
      - backendtlspolicies/status
      - tlsroutes/status
      - listenersets/status
    verbs:
      - update
  - apiGroups:
      - gateway.nginx.org
    resources:
      - nginxgateways
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.nginx.org
    resources:
      - nginxproxies
      - clientsettingspolicies
      - observabilitypolicies
      - upstreamsettingspolicies
      - authenticationfilters
      - proxysettingspolicies
      - ratelimitpolicies
      - wafpolicies
    verbs:
      - list
      - watch
  - apiGroups:
      - gateway.nginx.org
    resources:
      - nginxgateways/status
      - clientsettingspolicies/status
      - observabilitypolicies/status
      - upstreamsettingspolicies/status
      - authenticationfilters/status
      - proxysettingspolicies/status
      - ratelimitpolicies/status
      - wafpolicies/status
    verbs:
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
