# SPDX-FileCopyrightText: © 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
# Source: nginx-gateway-fabric/templates/nginxgateway.yaml
apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  name: nginx-gw-controller-config
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.5.1
    app.kubernetes.io/name: nginx-gw-controller
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  logging:
    level: info
  name: nginx-gw-config
