# SPDX-FileCopyrightText: © 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
# Source: nginx-gateway-fabric/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gw
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.6.3
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.6.3"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
automountServiceAccountToken: false
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gw-controller-cert-generator
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.6.3
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.6.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
automountServiceAccountToken: false
