<<<<<<< HEAD
# SPDX-FileCopyrightText: © 2024 Siemens Healthineers AG
=======
# SPDX-FileCopyrightText: © 2026 Siemens Healthineers AG
>>>>>>> origin/main
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-cluster-master-pv
  namespace: logging
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /logging
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
<<<<<<< HEAD
=======
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubemaster
>>>>>>> origin/main
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
<<<<<<< HEAD
---
=======
---
>>>>>>> origin/main
