# SPDX-FileCopyrightText: © 2024 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

ARG WINDOWS_VERSION

FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

LABEL description='diskwriter Tool'

COPY ["/dist/diskwriter.exe", "/diskwriter.exe"]