graph TD
    CallScript["'c\k\smallsetup\helpers\Buildk2sZipPackage.ps1\n [-Proxy myProxy]\n -TargetDirectory myExistingDirectory\n -ZipPackageFileName myZipPackage.zip\n [-ForOfflineInstallation]'"] --> if_for_offline{for offline\n installation?}
    if_for_offline -->|no| AddBaseImageToExclusionList("Include c\k\bin\Kubemaster-Base.vhdx to exclusion list")
    if_for_offline -->|yes| if_baseImage_available{"c\k\bin\Kubemaster-Base.vhdx\n exists?"}
    if_baseImage_available -->|yes| GetFilesAndDirectories
    if_baseImage_available -->|no| BuildAndProvisionKubemasterBaseImage
    AddBaseImageToExclusionList --> GetFilesAndDirectories
    BuildAndProvisionKubemasterBaseImage("Build and provision base image") --> GetFilesAndDirectories
    GetFilesAndDirectories("Get a list with all files and directories") --> FilterByExclusionList
    FilterByExclusionList("Remove files and directories from list according to exclusion list") --> CreateZipPackage
    CreateZipPackage("Create zip package") --> PopulateZipPackage("Populate zip package with directories and files")